export const TABLES = [
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT NOT NULL,
    role TEXT NOT NULL,
    active BOOLEAN DEFAULT 1,
    email TEXT,
    avatar_initials TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS products (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    status TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    description TEXT,
    icon TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS releases (
    id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL,
    version TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    target_date TEXT NOT NULL,
    released_date TEXT,
    description TEXT,
    features_json TEXT NOT NULL,
    server_upgrades TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL,
    priority TEXT NOT NULL,
    assignee_id TEXT NOT NULL,
    product_id TEXT,
    release_id TEXT,
    due_date TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS uat_cases (
    id TEXT PRIMARY KEY,
    release_id TEXT NOT NULL,
    product_id TEXT,
    title TEXT NOT NULL,
    description TEXT,
    result TEXT NOT NULL,
    assignee_id TEXT,
    notes TEXT,
    attachment_name TEXT,
    attachment_data TEXT,
    attachment_size INTEGER,
    sp_item_id TEXT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS release_signoffs (
    release_id TEXT NOT NULL,
    signed_off_by TEXT NOT NULL,
    signed_off_at DATETIME NOT NULL,
    notes TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS interfaces (
    id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    endpoint TEXT NOT NULL,
    service_provider TEXT,
    target_audience TEXT,
    direction TEXT DEFAULT 'Provided',
    connection_details TEXT,
    owner_id TEXT NOT NULL,
    status TEXT NOT NULL,
    description TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS apis (
    id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL,
    name TEXT NOT NULL,
    method TEXT NOT NULL,
    endpoint TEXT NOT NULL,
    auth_type TEXT NOT NULL,
    client_id TEXT,
    scope TEXT,
    api_key_meta TEXT,
    given_to TEXT NOT NULL,
    rate_limit TEXT,
    owner_id TEXT NOT NULL,
    status TEXT NOT NULL,
    description TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS secrets_meta (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    last_rotated_at DATETIME NOT NULL,
    last_accessed_at DATETIME,
    last_accessed_by TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS hr_records (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    status TEXT NOT NULL,
    work_location TEXT DEFAULT 'Office',
    leave_from TEXT,
    leave_to TEXT,
    phone TEXT,
    emergency_contact TEXT,
    skills_tags TEXT,
    notes TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS schedule_events (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    type TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT,
    linked_id TEXT,
    linked_type TEXT,
    notify_at TEXT,
    notified BOOLEAN DEFAULT 0,
    created_by TEXT NOT NULL,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS documents_meta (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    product_id TEXT,
    owner_id TEXT NOT NULL,
    version TEXT,
    description TEXT,
    drive_item_id TEXT NOT NULL,
    web_url TEXT NOT NULL,
    last_modified DATETIME NOT NULL,
    file_size INTEGER,
    mime_type TEXT,
    file_name TEXT,
    file_data TEXT,
    sharepoint_status TEXT DEFAULT 'Pending',
    linked_entity_type TEXT,
    linked_entity_id TEXT,
    linked_entity_name TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS audit_log (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    action TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    detail TEXT,
    ip_address TEXT,
    sp_item_id TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS plugin_configs (
    plugin_id TEXT PRIMARY KEY,
    settings_json TEXT NOT NULL,
    status TEXT NOT NULL,
    connected_as TEXT,
    connected_at DATETIME,
    error TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS sync_state (
    entity TEXT PRIMARY KEY,
    last_sync_at DATETIME,
    version INTEGER DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS local_mutations (
    id TEXT PRIMARY KEY,
    entity TEXT NOT NULL,
    sp_item_id TEXT,
    operation TEXT NOT NULL,
    payload_json TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    synced BOOLEAN DEFAULT 0
  )`,
  `CREATE TABLE IF NOT EXISTS product_custom_sections (
    id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL,
    title TEXT NOT NULL,
    section_type TEXT NOT NULL,
    content_json TEXT NOT NULL,
    icon TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS product_team_members (
    id TEXT PRIMARY KEY,
    product_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role_in_product TEXT DEFAULT 'Contributor',
    assigned_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(product_id, user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS user_notifications (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT,
    type TEXT DEFAULT 'Assignment',
    entity_type TEXT,
    entity_id TEXT,
    read INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_unotif_user ON user_notifications(user_id, read)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_product ON tasks(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_tasks_release ON tasks(release_id)`,
  `CREATE INDEX IF NOT EXISTS idx_releases_product ON releases(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_uat_release ON uat_cases(release_id)`,
  `CREATE INDEX IF NOT EXISTS idx_uat_product ON uat_cases(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_interfaces_product ON interfaces(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_apis_product ON apis(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_docs_product ON documents_meta(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_sections_product ON product_custom_sections(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_ptm_product ON product_team_members(product_id)`,
  `CREATE INDEX IF NOT EXISTS idx_mutations_synced ON local_mutations(synced, created_at)`
];
